# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{atok-twitter}
  s.version = "0.1.0"
  s.platform = %q{x86-mswin32}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["MIKAMI Yoshiyuki"]
  s.date = %q{2009-11-24}
  s.default_executable = %q{atok-twitter-install}
  s.description = %q{Twitter client on ATOK.}
  s.email = %q{yoshuki@saikyoline.jp}
  s.executables = ["atok-twitter-install"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "atok-twitter.gemspec",
     "bin/atok-twitter-install",
     "lib/atok/twitter/installer.rb",
     "plugin/ATOK_PLUGIN_MESSAGE.DLL",
     "plugin/DATA/twitter.xml",
     "plugin/DATA/twitter_wo_login_info.rb",
     "plugin/SETUP.EXE",
     "plugin/SETUPINFO.XML",
     "spec/atok-twitter_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/yoshuki/atok-twitter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Twitter client on ATOK.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/atok-twitter_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.0"])
  end
end

